version: '3.3'

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "1236:1236"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui

  lemmy:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8536:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
      - LEMMY_CONFIG_LOCATION=/config/config.hjson
    volumes:
      - ../lemmy.hjson:/config/config.hjson
      - ../../:/workspace
    #command: ["cargo","run"]
    # uncomment the above if you just want to run lemmy as is
    

    depends_on: 
      - pictrs
      - postgres

  lemmy-ui:
    image: dessalines/lemmy-ui:0.14.3
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=localhost:1234
      - LEMMY_HTTPS=false
    depends_on: 
      - lemmy

  postgres:
    image: postgres:12-alpine
    ports:
      # use a different port so it doesnt conflict with postgres running on the host
      - "5433:5432"
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:v0.2.6-r2
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
